@echo off
echo Updating pip...
python -m pip install --upgrade pip
echo Installing requirements...
python -m pip install -r requirements.txt
echo Starting backend...
python -m uvicorn app.main:app --reload --port 8000
pause